
server:
  port: 9090

#spring:
#  security:
#    saml2:
#      relyingparty:
#        registration:
#          okta-saml:
#            identityprovider:
#              entity-id: http://www.okta.com/exk9o5guploxo6hK45d7
#              verification:
#                credentials:
#                - certificate-location: "classpath:okta.crt"
#              singlesignon:
#                url: https://dev-77409672.okta.com/app/dev-77409672_devbms_1/exk9o5guploxo6hK45d7/sso/saml
#                sign-request: false
